### ISSUE TITLE
Stuck!

### ISSUE THREAD

**Issue by skypatel0503** [RahulShaw/ITPROTV-DL#2]
Do u have any Idea why it is stuck? and not download any files.

![image](https://user-images.githubusercontent.com/42603704/105626438-9336b800-5e55-11eb-83f2-bb9423d89fc2.png)

**Comment by RahulShaw** [comment]
Do you have an active subscription on itpro.tv?

**Comment by skypatel0503** [comment]
Yes, I have and it will expire in end of this month.

**Comment by RahulShaw** [comment]
Unfortunately, I don't have an active subscription at the moment to check and fix the issue. 
However, if you're okay then you may share yours and I promise no unfair usage. 
Feel free to write to me here - rahulshaw@protonmail.com

**Comment by dexter101010** [comment]
> Do u have any Idea why it is stuck? and not download any files.
> 
> ![image](https://user-images.githubusercontent.com/42603704/105626438-9336b800-5e55-11eb-83f2-bb9423d89fc2.png)

The script it is working. The issues is that you have a very poor internet connection. Yes, the script can be improved but at this moment , the script it is working!

**Comment by skypatel0503** [comment]
Great!

**Comment by retardedloozer** [comment]
Does this script work for free weekends? Cause I have the same stuck problem

EDIT: I can confirm it works for free weekends. Just used this tool to get the LPIC-1 course since its free for a weekend.

I had to make sure that the ChromeDriver I downloaded was the same version as the Google Chrome I downloaded. 

Also @RahulShaw you should add to your README that this script requires that you have Google Chrome installed in the default directory. I was getting errors with the ChromeDriver that the Chrome binary couldn't be found (I thought I could use any chromium browser). It's not the case

**Comment by iLaurian** [comment]
I am stuck too and is wierd because the first 5 links and sources worked very fast and my internet connection is good. Did it worked for you till the end? And how long did it take?

Executing for https://app.itpro.tv/course/certified-ethical-hacker-v11/overview-ceh11
* Trying to log in ... *
Cookies baked!
 - Logged in!
Course name detected as Course Certified Ethical Hacker (CEH) v11
Enumerating links and sources ...
Progress: 5 of 147
